<?php
/**
 *  Autoloader function generated by crodas/Autoloader
 *
 *  https://github.com/crodas/Autoloader
 *
 *  This is a generated file, do not modify it.
 */

#* if ($stats)
$GLOBALS['call___stats__'] = 0;
$GLOBALS['load___stats__'] = 0;
#* end

#* function validate($var)
if (!class_exists($__var__, false) #* if ($hasInterface) *# && !interface_exists($__var__, false)#* end if ($hasTraits) *# && !trait_exists($__var__, false) #* end  *#) {
#* end


spl_autoload_register(function ($class) {
    #* $classes = @$classes;
    #* $deps    = @$deps;
    /*
        This array has a map of (class => file)
    */

    // classes {{{
    static $classes = __classes__;
    // }}}

    // deps {{{
    static $deps    = __deps__;
    // }}}

    $class = strtolower($class);
    if (isset($classes[$class])) {
        #* if ($stats) 
        $GLOBALS['call___stats__']++;
        $GLOBALS['load___stats__']++;
        #* end
        if (!empty($deps[$class])) {
            foreach ($deps[$class] as $zclass) {
                #* validate('zclass')
                    #* if ($stats) 
                    $GLOBALS['load___stats__']++;
                    #* end
                    #* if ($relative)
                    require __DIR__  . $classes[$zclass];
                    #* else
                    require $classes[$zclass];
                    #* end
                }
            }
        }

        #* validate('class')
            #* if ($relative)
            require __DIR__  . $classes[$class];
            #* else
            require $classes[$class];
            #* end
        }
        return true;
    }

    #* if ($include_psr0)
    /**
     * Autoloader that implements the PSR-0 spec for interoperability between
     * PHP software.
     *
     * kudos to @alganet for this autoloader script.
     * borrowed from https://github.com/Respect/Validation/blob/develop/tests/bootstrap.php
     */
    $fileParts = explode('\\', ltrim($class, '\\'));
    if (false !== strpos(end($fileParts), '_')) {
        array_splice($fileParts, -1, 1, explode('_', current($fileParts)));
    }
    $file = stream_resolve_include_path(implode(DIRECTORY_SEPARATOR, $fileParts) . '.php');
    if ($file) {
        return require $file;
    }
    #* end
    return false;
} #* if (!$relative)
, true, true #* end 
);


#* if ($stats)
function get__stats__() {
    global $load___stats__, $call___stats__;
    return array('loaded' => $load___stats__, 'calls' => $call___stats__);
}
#* end
