<?php
/**
 *  Autoloader function generated by crodas/Autoloader
 *
 *  https://github.com/crodas/Autoloader
 *
 *  This is a generated file, do not modify it.
 */

spl_autoload_register(function ($class) {
    /*
        This array has a map of (class => file)
    */

    // classes {{{
    static $classes = array (
  'autoloader\\cliapp' => '/home/crodas/projects/newest/Autoloader/lib/Autoloader/CliApp.php',
  'autoloader\\generator' => '/home/crodas/projects/newest/Autoloader/lib/Autoloader/Generator.php',
  'autoloader\\composer' => '/home/crodas/projects/newest/Autoloader/lib/Autoloader/Composer.php',
);
    // }}}


    $class = strtolower($class);
    if (isset($classes[$class])) {

        if (is_array($class)) {

            if (!$class[1]($class[0], false)) {

                require $classes[$class[0]];

            }

        } else if (!class_exists($class, false)) {

            require $classes[$class];

        }
        return true;
    }

    /**
     * Autoloader that implements the PSR-0 spec for interoperability between
     * PHP software.
     *
     * kudos to @alganet for this autoloader script.
     * borrowed from https://github.com/Respect/Validation/blob/develop/tests/bootstrap.php
     */
    $fileParts = explode('\\', ltrim($class, '\\'));
    if (false !== strpos(end($fileParts), '_')) {
        array_splice($fileParts, -1, 1, explode('_', current($fileParts)));
    }
    $file = stream_resolve_include_path(implode(DIRECTORY_SEPARATOR, $fileParts) . '.php');
    if ($file) {
        return require $file;
    }
    return false;
}, true, true);


