<?php
/**
 *  This file was generated with crodas/SimpleView (https://github.com/crodas/SimpleView)
 *  Do not edit this file.
 *
 */

namespace {


    $GLOBALS['file_54dceccad5f97'] = array();
    $GLOBALS['line_54dceccad5f97'] = array();

    class base_template_aab8d954813d6a190dfedd5e726e6f8ed2ef081e
    {
        protected $parent;
        protected $child;
        protected $context;

        public function yield_parent($name, $args)
        {
            $method = "section_" . sha1($name);

            if (is_callable(array($this->parent, $method))) {
                $this->parent->$method(array_merge($this->context, $args));
                return true;
            }

            if ($this->parent) {
                return $this->parent->yield_parent($name, $args);
            }

            return false;
        }

        public function do_yield($name, Array $args = array())
        {
            if ($this->child) {
                // We have a children template, we are their base
                // so let's see if they have implemented by any change
                // this section
                if ($this->child->do_yield($name, $args)) {
                    // yes!
                    return true;
                }
            }

            // Do I have this section defined?
            $method = "section_" . sha1($name);
            if (is_callable(array($this, $method))) {
                // Yes!
                $this->$method(array_merge($this->context, $args));
                return true;
            }

            // No :-(
            return false;
        }

    }

    /** 
     *  Template class generated from load.tpl.php
     */
    class class_e516b5d47b06ed172138f3ca3ffbb2cc7d52a85a extends base_template_aab8d954813d6a190dfedd5e726e6f8ed2ef081e
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Autoloader\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54dceccad5f97, $line_54dceccad5f97;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54dceccad5f97 = array_push($file_54dceccad5f97, 'load.tpl.php') - 1;
            $line_54dceccad5f97[$_54dceccad5f97] = 1;

            echo "\$class = strtolower(\$class);\nif (isset(\$classes[\$class])) {\n";
            $line_54dceccad5f97[$_54dceccad5f97] = 3;
            if ($stats) {
                $line_54dceccad5f97[$_54dceccad5f97] = 4;
                echo "        \$GLOBALS['call_" . ($stats) . "']++;\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 5;
            }
            $line_54dceccad5f97[$_54dceccad5f97] = 6;
            if (count($deps) > 0) {
                $line_54dceccad5f97[$_54dceccad5f97] = 7;
                echo "    if (!empty(\$deps[\$class])) {\n        foreach (\$deps[\$class] as \$zclass) {\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 9;
                Autoloader\Templates::exec("validate", array('var' => 'zclass'), $this->context);
                $line_54dceccad5f97[$_54dceccad5f97] = 10;
                echo "        }\n    }\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 12;
            }
            $line_54dceccad5f97[$_54dceccad5f97] = 13;
            Autoloader\Templates::exec("validate", array('var' => 'class'), $this->context);
            $line_54dceccad5f97[$_54dceccad5f97] = 14;
            echo "    return true;\n}\n";

            array_pop($file_54dceccad5f97);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from index.tpl.php
     */
    class class_a3ffbb3ad03f81c3fd1d93e6556beae4811dc590 extends base_template_aab8d954813d6a190dfedd5e726e6f8ed2ef081e
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Autoloader\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54dceccad5f97, $line_54dceccad5f97;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54dceccad5f97 = array_push($file_54dceccad5f97, 'index.tpl.php') - 1;
            $line_54dceccad5f97[$_54dceccad5f97] = 1;

            echo "<?php\n/**\n *  Autoloader function generated by crodas/Autoloader\n *\n *  https://github.com/crodas/Autoloader\n *\n *  This is a generated file, do not modify it.\n */\n\nspl_autoload_register(function(\$class) {\n    static \$loaded     = array();\n    static \$namespaces = ";
            $line_54dceccad5f97[$_54dceccad5f97] = 12;
            var_export($filemap);
            echo ";\n\n    \$class = strtolower(\$class);\n\n    foreach (\$namespaces as \$namespace => \$file) {\n        if (\$namespace !== '-all' && strpos(\$class, \$namespace) !== 0) {\n            // wrong namespace move forward!\n            continue;\n        }\n\n        if (empty(\$loaded[\$namespace])) {\n";
            $line_54dceccad5f97[$_54dceccad5f97] = 23;
            if ($relative) {
                $line_54dceccad5f97[$_54dceccad5f97] = 24;
                echo "            \$loaded[\$namespace] = require __DIR__ . \$file;\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 25;
            }
            else {
                $line_54dceccad5f97[$_54dceccad5f97] = 26;
                echo "            \$loaded[\$namespace] = require \$file;\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 27;
            }
            $line_54dceccad5f97[$_54dceccad5f97] = 28;
            echo "        }\n        return \$loaded[\$namespace]( \$class );\n    }\n});\n\n";

            array_pop($file_54dceccad5f97);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from autoloader.tpl.php
     */
    class class_0e0b04df3e4434b3998ba2ae1d44780d04317374 extends base_template_aab8d954813d6a190dfedd5e726e6f8ed2ef081e
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Autoloader\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54dceccad5f97, $line_54dceccad5f97;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54dceccad5f97 = array_push($file_54dceccad5f97, 'autoloader.tpl.php') - 1;
            $line_54dceccad5f97[$_54dceccad5f97] = 1;

            echo "<?php\n/**\n *  Autoloader function generated by crodas/Autoloader\n *\n *  https://github.com/crodas/Autoloader\n *\n *  This is a generated file, do not modify it.\n */\n";
            $line_54dceccad5f97[$_54dceccad5f97] = 9;
            if ($stats) {
                $line_54dceccad5f97[$_54dceccad5f97] = 10;
                echo "\$GLOBALS['call_" . ($stats) . "'] = 0;\n\$GLOBALS['load_";
                $line_54dceccad5f97[$_54dceccad5f97] = 11;
                echo $stats . "'] = 0;\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 12;
            }
            $line_54dceccad5f97[$_54dceccad5f97] = 13;
            echo "\nspl_autoload_register(function (\$class) {\n    /*\n        This array has a map of (class => file)\n    */\n    static \$classes = ";
            $line_54dceccad5f97[$_54dceccad5f97] = 18;
            var_export($classes);
            echo ";\n\n";
            $line_54dceccad5f97[$_54dceccad5f97] = 20;
            if (count($deps) > 0) {
                $line_54dceccad5f97[$_54dceccad5f97] = 21;
                echo "    static \$deps    = ";
                var_export($deps);
                echo ";\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 22;
            }
            $line_54dceccad5f97[$_54dceccad5f97] = 23;
            echo "\n";
            $line_54dceccad5f97[$_54dceccad5f97] = 24;
            Autoloader\Templates::exec("load", $this->context);
            $line_54dceccad5f97[$_54dceccad5f97] = 25;
            echo "\n";
            $line_54dceccad5f97[$_54dceccad5f97] = 26;
            if ($include_psr0) {
                $line_54dceccad5f97[$_54dceccad5f97] = 27;
                echo "    /**\n     * Autoloader that implements the PSR-0 spec for interoperability between\n     * PHP software.\n     *\n     * kudos to";
                $line_54dceccad5f97[$_54dceccad5f97] = 31;
                echo "@" . "alganet for this autoloader script.\n     * borrowed from https://github.com/Respect/Validation/blob/develop/tests/bootstrap.php\n     */\n    \$fileParts = explode('\\\\', ltrim(\$class, '\\\\'));\n    if (false !== strpos(end(\$fileParts), '_')) {\n        array_splice(\$fileParts, -1, 1, explode('_', current(\$fileParts)));\n    }\n    \$file = stream_resolve_include_path(implode(DIRECTORY_SEPARATOR, \$fileParts) . '.php');\n    if (\$file) {\n        return require \$file;\n    }\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 42;
            }
            $line_54dceccad5f97[$_54dceccad5f97] = 43;
            echo "\n    return false;\n} \n";
            $line_54dceccad5f97[$_54dceccad5f97] = 46;
            if (!$relative) {
                $line_54dceccad5f97[$_54dceccad5f97] = 47;
                echo ", true, true\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 48;
            }
            $line_54dceccad5f97[$_54dceccad5f97] = 49;
            echo ");\n\n";
            $line_54dceccad5f97[$_54dceccad5f97] = 51;
            if ($stats) {
                $line_54dceccad5f97[$_54dceccad5f97] = 52;
                echo "function get" . ($stats) . "() {\n    global \$load_";
                $line_54dceccad5f97[$_54dceccad5f97] = 53;
                echo $stats . ", \$call_" . ($stats) . ";\n    return array('loaded' => \$load_";
                $line_54dceccad5f97[$_54dceccad5f97] = 54;
                echo $stats . ", 'calls' => \$call_" . ($stats) . ");\n}\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 56;
            }
            $line_54dceccad5f97[$_54dceccad5f97] = 57;

            array_pop($file_54dceccad5f97);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from validate.tpl.php
     */
    class class_5df81830c135da22bb7e6b9a266d6801c6bfeb2f extends base_template_aab8d954813d6a190dfedd5e726e6f8ed2ef081e
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Autoloader\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54dceccad5f97, $line_54dceccad5f97;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54dceccad5f97 = array_push($file_54dceccad5f97, 'validate.tpl.php') - 1;
            $line_54dceccad5f97[$_54dceccad5f97] = 1;

            echo "if (\n    ! \$classes[\$";
            $line_54dceccad5f97[$_54dceccad5f97] = 2;
            echo $var . "][1]( \$" . ($var) . ", false )\n) {\n";
            $line_54dceccad5f97[$_54dceccad5f97] = 4;
            if ($stats) {
                $line_54dceccad5f97[$_54dceccad5f97] = 5;
                echo "    \$GLOBALS['load_" . ($stats) . "']++;\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 6;
            }
            $line_54dceccad5f97[$_54dceccad5f97] = 7;
            if ($relative) {
                $line_54dceccad5f97[$_54dceccad5f97] = 8;
                echo "    require __DIR__  . \$classes[\$" . ($var) . "][0];\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 9;
            }
            else {
                $line_54dceccad5f97[$_54dceccad5f97] = 10;
                echo "    require \$classes[\$" . ($var) . "][0];\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 11;
            }
            $line_54dceccad5f97[$_54dceccad5f97] = 12;
            echo "}\n";

            array_pop($file_54dceccad5f97);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from namespace.tpl.php
     */
    class class_31028f15e50ec3b9927c300a53d04bb713e73e85 extends base_template_aab8d954813d6a190dfedd5e726e6f8ed2ef081e
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Autoloader\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54dceccad5f97, $line_54dceccad5f97;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54dceccad5f97 = array_push($file_54dceccad5f97, 'namespace.tpl.php') - 1;
            $line_54dceccad5f97[$_54dceccad5f97] = 1;

            echo "<?php\n/**\n *  Autoloader function generated by crodas/Autoloader\n *\n *  https://github.com/crodas/Autoloader\n *\n *  This is a generated file, do not modify it.\n */\n\nreturn function(\$class) {\n    static \$classes = ";
            $line_54dceccad5f97[$_54dceccad5f97] = 11;
            echo var_export($classes, true) . ";\n\n";
            $line_54dceccad5f97[$_54dceccad5f97] = 13;
            if (count($deps) > 0) {
                $line_54dceccad5f97[$_54dceccad5f97] = 14;
                echo "    static \$deps    = " . (var_export($deps, true)) . ";\n";
                $line_54dceccad5f97[$_54dceccad5f97] = 15;
            }
            $line_54dceccad5f97[$_54dceccad5f97] = 16;
            echo "\n";
            $line_54dceccad5f97[$_54dceccad5f97] = 17;
            Autoloader\Templates::exec("load", $this->context);
            $line_54dceccad5f97[$_54dceccad5f97] = 18;
            echo "\n    return false;\n};\n\n";

            array_pop($file_54dceccad5f97);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

}

namespace Autoloader {

    use Exception;

    class ExceptionWrapper extends Exception
    {
        public $e;
        protected $file;

        public function getSimpleViewTrace()
        {
            global $file_54dceccad5f97, $line_54dceccad5f97;

            $traces = $this->e->getTrace();
            $i = 0;
            foreach ($traces as &$trace) {
                if (!empty($trace['file'])
                    && $trace['file'] == $this->file && !empty($file_54dceccad5f97[$i])) {
                    $trace['file'] = $file_54dceccad5f97[$i];
                    $trace['line'] = $line_54dceccad5f97[$i];
                    ++$i;
                }
                if (empty($trace['file'])) {
                    $trace['file'] = '[internal function]';
                }
                if (empty($trace['line'])) {
                    $trace['line'] = '';
                }
            }

            return $traces;
        }

        public function __toString()
        {
            $traces = $this->getSimpleViewTrace();
            $str    = "exception '" . get_class($this->e) . "' in {$traces[0]['file']}{$traces[0]['line']}:\nStack trace:\n";
            foreach ($traces as $i => $trace) {
                $str .= "#{$i} {$trace['file']}:{$trace['line']}\n";
            }
            ++$i;
            $str .= "#{$i} {main}";
            return $str;
        }

        public function __construct(Exception $e, $file)
        {
            $this->e    = $e;
            $this->file = $file;
        }
    }


    class Templates
    {
        public static function getAll()
        {
            return array (
                0 => 'load',
                1 => 'index',
                2 => 'autoloader',
                3 => 'validate',
                4 => 'namespace',
            );
        }

        public static function getAllSections($name, $fail = true)
        {
            switch ($name) {
            default:
                if ($fail) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }

                return array();
            }
        }

        public static function exec($name, Array $context = array(), Array $global = array())
        {
            $tpl = self::get($name);
            return $tpl->render(array_merge($global, $context));
        }

        public static function get($name, Array $context = array())
        {
            static $classes = array (
                'load.tpl.php' => 'class_e516b5d47b06ed172138f3ca3ffbb2cc7d52a85a',
                'load' => 'class_e516b5d47b06ed172138f3ca3ffbb2cc7d52a85a',
                'index.tpl.php' => 'class_a3ffbb3ad03f81c3fd1d93e6556beae4811dc590',
                'index' => 'class_a3ffbb3ad03f81c3fd1d93e6556beae4811dc590',
                'autoloader.tpl.php' => 'class_0e0b04df3e4434b3998ba2ae1d44780d04317374',
                'autoloader' => 'class_0e0b04df3e4434b3998ba2ae1d44780d04317374',
                'validate.tpl.php' => 'class_5df81830c135da22bb7e6b9a266d6801c6bfeb2f',
                'validate' => 'class_5df81830c135da22bb7e6b9a266d6801c6bfeb2f',
                'namespace.tpl.php' => 'class_31028f15e50ec3b9927c300a53d04bb713e73e85',
                'namespace' => 'class_31028f15e50ec3b9927c300a53d04bb713e73e85',
            );
            $name = strtolower($name);
            if (empty($classes[$name])) {
                throw new \RuntimeException("Cannot find template $name");
            }

            $class = "\\" . $classes[$name];
            return new $class;
        }
    }

}
