<?php
/**
 *  Autoloader function generated by crodas/Autoloader
 *
 *  https://github.com/crodas/Autoloader
 *
 *  This is a generated file, do not modify it.
 */
$GLOBALS['call_complexstat'] = 0;
$GLOBALS['load_complexstat'] = 0;

spl_autoload_register(function ($class) {
    /*
        This array has a map of (class => file)
    */

    // classes {{{
    static $classes = array (
  'foointerface' => '/home/crodas/projects/newest/Autoloader/tests/fixtures/complex/interface.php',
  'barinterface' => '/home/crodas/projects/newest/Autoloader/tests/fixtures/complex/interface1.php',
  'autoloader\\test\\complex\\complex' => '/home/crodas/projects/newest/Autoloader/tests/fixtures/complex/Foo.php',
  'simple' => '/home/crodas/projects/newest/Autoloader/tests/fixtures/complex/Bar.php',
  'autoloader\\test\\complex\\xxxfoobar' => '/home/crodas/projects/newest/Autoloader/tests/fixtures/complex/anotherInterface.php',
  'xxxinterface' => '/home/crodas/projects/newest/Autoloader/tests/fixtures/complex/interface2.php',
);
    // }}}

    // deps {{{
    static $deps    = array (
  'foointerface' => 
  array (
    0 => 
    array (
      0 => 'xxxinterface',
      1 => 'interface_exists',
    ),
    1 => 
    array (
      0 => 'barinterface',
      1 => 'interface_exists',
    ),
  ),
  'barinterface' => 
  array (
    0 => 
    array (
      0 => 'xxxinterface',
      1 => 'interface_exists',
    ),
  ),
  'autoloader\\test\\complex\\complex' => 
  array (
    0 => 
    array (
      0 => 'autoloader\\test\\complex\\xxxfoobar',
      1 => 'interface_exists',
    ),
    1 => 
    array (
      0 => 'xxxinterface',
      1 => 'interface_exists',
    ),
    2 => 
    array (
      0 => 'barinterface',
      1 => 'interface_exists',
    ),
    3 => 
    array (
      0 => 'foointerface',
      1 => 'interface_exists',
    ),
    4 => 
    array (
      0 => 'simple',
      1 => 'class_exists',
    ),
  ),
);
    // }}}

    $class = strtolower($class);
    if (isset($classes[$class])) {
        $GLOBALS['call_complexstat']++;
        if (!empty($deps[$class])) {
            foreach ($deps[$class] as $zclass) {
                if (is_array($zclass)) {
                    if (!$zclass[1]($zclass[0], false)) {
                        $GLOBALS['load_complexstat']++;
                        require $classes[$zclass[0]];
                    }
                } else if (!class_exists($zclass, false)) {
                    $GLOBALS['load_complexstat']++;
                    require $classes[$zclass];
                }
            }
        }

        if (is_array($class)) {

            if (!$class[1]($class[0], false)) {

                $GLOBALS['load_complexstat']++;

                require $classes[$class[0]];

            }

        } else if (!class_exists($class, false)) {

            $GLOBALS['load_complexstat']++;

            require $classes[$class];

        }
        return true;
    }

    /**
     * Autoloader that implements the PSR-0 spec for interoperability between
     * PHP software.
     *
     * kudos to @alganet for this autoloader script.
     * borrowed from https://github.com/Respect/Validation/blob/develop/tests/bootstrap.php
     */
    $fileParts = explode('\\', ltrim($class, '\\'));
    if (false !== strpos(end($fileParts), '_')) {
        array_splice($fileParts, -1, 1, explode('_', current($fileParts)));
    }
    $file = stream_resolve_include_path(implode(DIRECTORY_SEPARATOR, $fileParts) . '.php');
    if ($file) {
        return require $file;
    }
    return false;
}, true, true);


function getcomplexstat() {
    global $load_complexstat, $call_complexstat;
    return array('loaded' => $load_complexstat, 'calls' => $call_complexstat);
}
