<?php
/**
 *  Autoloader function generated by crodas/Autoloader
 *
 *  https://github.com/crodas/Autoloader
 *
 *  This is a generated file, do not modify it.
 */
@set($function, 'index_' . $hash)
@if ($relative)
@set($dir, '__DIR__' . $hash)
define({{@$dir}}, defined('__DIR__') ? __DIR__ : dirname(__FILE__));
@endif

function {{$function}}($class) {
    static $loaded     = array();
    static $namespaces = {{ @$filemap}};
    static $functions  = {{ @$functions }};

    $class = strtolower($class);

    foreach ($namespaces as $namespace => $file) {
        if ($namespace !== '-all' && strpos($class, $namespace) !== 0) {
            // wrong namespace move forward!
            continue;
        }

        if (empty($loaded[$namespace])) {
            @if ($relative)
            $loaded[$namespace] = require {{$dir}} . $file;
            @else
            $loaded[$namespace] = require $file;
            @end
        }
        return $loaded[$namespace]( $class );
    }
}

spl_autoload_register({{@$function}});

@foreach ($includes as $include)
    @if ($relative)
        require_once __DIR__ . {{@$include}};
    @else
        require_once {{@$include}};
    @end
@end
