<?php
/**
 *  Autoloader function generated by crodas/Autoloader
 *
 *  https://github.com/crodas/Autoloader
 *
 *  This is a generated file, do not modify it.
 */

return function($class) {
    static $classes = {{ var_export($classes, true) }};

    @if (count($deps) > 0)
    static $deps    = {{ var_export($deps, true) }};
    @end

    @include("load")

    return false;
};

