<?php
/**
 *  Autoloader function generated by crodas/Autoloader
 *
 *  https://github.com/crodas/Autoloader
 *
 *  This is a generated file, do not modify it.
 */

@set($function, 'autoloader_' . uniqid(true));
@if ($relative)
@set($dir, '__DIR__' . uniqid(true));
define({{@$dir}}, defined('__DIR__') ? __DIR__ : dirname(__FILE__));
@endif

function {{$function}}($class) {
    static $classes = {{ var_export($classes, true) }};

    @if (count($deps) > 0)
    static $deps    = {{ var_export($deps, true) }};
    @end

    @include("load")

    return false;
}

return {{@$function}};
